server:
  port: 8080

spring:
  datasource:
    # URL: Usamos 'db' (nombre del servicio en compose) y el puerto interno 3306
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/proyecto?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    # Usuario: 'anon' definido en tu environment de MySQL
    username: ${SPRING_DATASOURCE_USERNAME:anon}
    # Password: '12345678aA!' definido en tu environment de MySQL
    password: ${SPRING_DATASOURCE_PASSWORD:12345678aA!}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jackson:
    serialization:
      fail-on-empty-beans: false
      indent-output: true
    generator:
      write-numbers-as-strings: false

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        # Dialecto actualizado para evitar el aviso de "deprecated"
        dialect: org.hibernate.dialect.MySQLDialect
        setup_osiv: false 

app:
  jwt:
    secret: ${JWT_SECRET:V9sK2F4L8QpR0E3TnX6B1ZC5H7MJAUYDWPASDFGHJKLZXCVBN123456}
    ttlSeconds: 1800

security:
  lockout:
    maxAttempts: 5
    lockMinutes: 10